#include "sensors/tfmini.h"
#include "config.h"
#include "hardware/uart.h"
#include "hardware/pio.h"
#include "hardware/gpio.h"
#include "pico/stdlib.h"
#include "uart_rx.pio.h"   // auto-generated by pioasm from uart_rx.pio

// ----------------------------------------------------------------
//  PIO instance used for the Right TFMini sensor
// ----------------------------------------------------------------
static PIO  tf_pio    = pio0;
static uint tf_pio_sm = 0;      // state machine index (0-3)

// ----------------------------------------------------------------
//  Byte-read helpers
//    hw_getc  → hardware UART (blocking)
//    pio_getc → PIO soft-UART (blocking)
//  Both return the received byte.
// ----------------------------------------------------------------
static uint8_t hw_getc(uart_inst_t *u)
{
    while (!uart_is_readable(u))
        tight_loop_contents();
    return uart_getc(u);
}

static uint8_t pio_getc(void)
{
    return uart_rx_program_getc(tf_pio, tf_pio_sm);
}

// ----------------------------------------------------------------
//  Generic frame reader
//  'getc_fn' is either hw_getc(uart) or pio_getc() wrapped below.
// ----------------------------------------------------------------
typedef uint8_t (*getc_fn_t)(void *ctx);

// Wrappers so we can pass a uniform function pointer
static uint8_t getc_front(void *ctx) { (void)ctx; return hw_getc(TF_FRONT_UART); }
static uint8_t getc_left (void *ctx) { (void)ctx; return hw_getc(TF_LEFT_UART);  }
static uint8_t getc_right(void *ctx) { (void)ctx; return pio_getc();              }

static getc_fn_t getc_table[3] = { getc_front, getc_left, getc_right };

// ----------------------------------------------------------------
//  Parse one 9-byte TFMini frame.
//
//  Strategy: scan byte-by-byte looking for the 0x59 0x59 header.
//  This makes the reader self-synchronising after any corruption.
// ----------------------------------------------------------------
static bool parse_frame(getc_fn_t getc, void *ctx,
                        uint16_t *dist_mm, uint16_t *strength)
{
    uint8_t frame[9];
    uint8_t b;

    // ---- Find the first 0x59 header byte (with timeout) ----
    // At 115200 baud one frame = ~783 µs; allow 50 ms → ~64 frames.
    absolute_time_t deadline = make_timeout_time_ms(50);
    while (true) {
        if (absolute_time_diff_us(get_absolute_time(), deadline) < 0)
            return false;   // timeout
        b = getc(ctx);
        if (b == 0x59) break;
    }

    // ---- Collect the rest of the header and payload ----
    frame[0] = 0x59;
    frame[1] = getc(ctx);
    if (frame[1] != 0x59)
        return false;   // not a valid header pair — retry next call

    for (int i = 2; i < 9; i++)
        frame[i] = getc(ctx);

    // ---- Verify checksum ----
    uint8_t csum = 0;
    for (int i = 0; i < 8; i++)
        csum += frame[i];

    if (csum != frame[8])
        return false;   // checksum mismatch — drop frame

    // ---- Extract distance (cm → mm) and strength ----
    uint16_t dist_cm = (uint16_t)(frame[2]) | ((uint16_t)(frame[3]) << 8);
    uint16_t str     = (uint16_t)(frame[4]) | ((uint16_t)(frame[5]) << 8);

    // Strength < 100 means the reading is unreliable (weak return signal)
    if (str < 100)
        return false;

    *dist_mm  = dist_cm * 10u;
    *strength = str;
    return true;
}

// ----------------------------------------------------------------
//  Public API
// ----------------------------------------------------------------
void tfmini_init_all(void)
{
    // --- Front TFMini  → UART0, GP1 RX ---
    uart_init(TF_FRONT_UART, TFMINI_BAUD);
    gpio_set_function(TF_FRONT_RX_PIN, GPIO_FUNC_UART);
    uart_set_format(TF_FRONT_UART, 8, 1, UART_PARITY_NONE);
    uart_set_fifo_enabled(TF_FRONT_UART, true);

    // --- Left TFMini  → UART1, GP21 RX ---
    uart_init(TF_LEFT_UART, TFMINI_BAUD);
    gpio_set_function(TF_LEFT_RX_PIN, GPIO_FUNC_UART);
    uart_set_format(TF_LEFT_UART, 8, 1, UART_PARITY_NONE);
    uart_set_fifo_enabled(TF_LEFT_UART, true);

    // --- Right TFMini → PIO soft-UART, GP22 RX ---
    uint offset = pio_add_program(tf_pio, &uart_rx_program);
    uart_rx_program_init(tf_pio, tf_pio_sm, offset,
                         TF_RIGHT_PIO_RX, TFMINI_BAUD);
}

bool tfmini_read_frame(tf_id_t id, uint16_t *dist_mm, uint16_t *strength)
{
    return parse_frame(getc_table[id], NULL, dist_mm, strength);
}

uint16_t tfmini_get_distance(tf_id_t id)
{
    uint16_t dist = 0, strength = 0;
    if (tfmini_read_frame(id, &dist, &strength))
        return dist;
    return 0;   // 0 = invalid / no reading
}
